### ISSUE TITLE
Font used is not described

### ISSUE THREAD

**Issue by jamezpolley** [linuxaustralia/brand-guidelines#2]
I can't find any notes about the font used in the logo, and where that font should be used.

**Comment by KathyReid** [comment]
Good pickup @jamezpolley 
Att'd is more information on the logotype - the font is 'Cairo'
[Linux-Open-Source-logo-dev V4.pdf](https://github.com/linuxaustralia/brand-guidelines/files/2238365/Linux-Open-Source-logo-dev.V4.pdf)

https://fonts.google.com/specimen/Cairo

Did you want to add something in to cover this?

**Comment by KathyReid** [comment]
Updated README.md to reflect use of Cairo, thanks for the pickup
